name: CI_publish

on:
  push:
    tags: '**'
  workflow_dispatch:   # allows manual triggering

jobs:

  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Build artifacts
        run: |
          uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/